name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASS: ${{secrets.DOCKER_PASS}}
        run: |
            echo $DOCKER_PASS >> ~/pass.txt
            cat ~/pass.txt | docker login --username nilodna --password-stdin
      
      - name: building docker image
        run: | 
            docker build . --file ./Dockerfile.personal --tag nilodna/docker4roms:testCI
            docker images
        
      - name: docker push
        run: docker push nilodna/docker4roms
